### ISSUE TITLE
奉献一个又拍云空间

### ISSUE THREAD

**Issue by xiangpaopao** [suning-wireless/Pocket#10]
FTP空间，供放置静态资源和测试用

主机：v0.ftp.upyun.com
用户：msuning/msuning
密码：m.suning.com

对应URL http://msuning.b0.upaiyun.com/
注意又拍云空间有文件缓存，覆盖文件不会立即更新，建议直接改文件夹

**Comment by zhuxiaojian** [comment]
这个就不给你报销了，只能点个赞，水也没有的

**Comment by xiangpaopao** [comment]
@zhuxiaojian  这个是我靠脸得到的
